package defpackage;

import android.R;

/* loaded from: classes.dex */
public abstract class NG0 {
    public static final int[] a = {R.attr.background, R.attr.touchscreenBlocksFocus, R.attr.keyboardNavigationCluster, ru.mes.dnevnik.R.attr.elevation, ru.mes.dnevnik.R.attr.expanded, ru.mes.dnevnik.R.attr.liftOnScroll, ru.mes.dnevnik.R.attr.liftOnScrollColor, ru.mes.dnevnik.R.attr.liftOnScrollTargetViewId, ru.mes.dnevnik.R.attr.statusBarForeground};
    public static final int[] b = {ru.mes.dnevnik.R.attr.layout_scrollEffect, ru.mes.dnevnik.R.attr.layout_scrollFlags, ru.mes.dnevnik.R.attr.layout_scrollInterpolator};
    public static final int[] c = {R.attr.maxWidth, R.attr.maxHeight, R.attr.elevation, ru.mes.dnevnik.R.attr.backgroundTint, ru.mes.dnevnik.R.attr.behavior_draggable, ru.mes.dnevnik.R.attr.behavior_expandedOffset, ru.mes.dnevnik.R.attr.behavior_fitToContents, ru.mes.dnevnik.R.attr.behavior_halfExpandedRatio, ru.mes.dnevnik.R.attr.behavior_hideable, ru.mes.dnevnik.R.attr.behavior_peekHeight, ru.mes.dnevnik.R.attr.behavior_saveFlags, ru.mes.dnevnik.R.attr.behavior_significantVelocityThreshold, ru.mes.dnevnik.R.attr.behavior_skipCollapsed, ru.mes.dnevnik.R.attr.gestureInsetBottomIgnored, ru.mes.dnevnik.R.attr.marginLeftSystemWindowInsets, ru.mes.dnevnik.R.attr.marginRightSystemWindowInsets, ru.mes.dnevnik.R.attr.marginTopSystemWindowInsets, ru.mes.dnevnik.R.attr.paddingBottomSystemWindowInsets, ru.mes.dnevnik.R.attr.paddingLeftSystemWindowInsets, ru.mes.dnevnik.R.attr.paddingRightSystemWindowInsets, ru.mes.dnevnik.R.attr.paddingTopSystemWindowInsets, ru.mes.dnevnik.R.attr.shapeAppearance, ru.mes.dnevnik.R.attr.shapeAppearanceOverlay, ru.mes.dnevnik.R.attr.shouldRemoveExpandedCorners};
    public static final int[] d = {ru.mes.dnevnik.R.attr.carousel_alignment};
    public static final int[] e = {R.attr.textAppearance, R.attr.textSize, R.attr.textColor, R.attr.ellipsize, R.attr.maxWidth, R.attr.text, R.attr.checkable, ru.mes.dnevnik.R.attr.checkedIcon, ru.mes.dnevnik.R.attr.checkedIconEnabled, ru.mes.dnevnik.R.attr.checkedIconTint, ru.mes.dnevnik.R.attr.checkedIconVisible, ru.mes.dnevnik.R.attr.chipBackgroundColor, ru.mes.dnevnik.R.attr.chipCornerRadius, ru.mes.dnevnik.R.attr.chipEndPadding, ru.mes.dnevnik.R.attr.chipIcon, ru.mes.dnevnik.R.attr.chipIconEnabled, ru.mes.dnevnik.R.attr.chipIconSize, ru.mes.dnevnik.R.attr.chipIconTint, ru.mes.dnevnik.R.attr.chipIconVisible, ru.mes.dnevnik.R.attr.chipMinHeight, ru.mes.dnevnik.R.attr.chipMinTouchTargetSize, ru.mes.dnevnik.R.attr.chipStartPadding, ru.mes.dnevnik.R.attr.chipStrokeColor, ru.mes.dnevnik.R.attr.chipStrokeWidth, ru.mes.dnevnik.R.attr.chipSurfaceColor, ru.mes.dnevnik.R.attr.closeIcon, ru.mes.dnevnik.R.attr.closeIconEnabled, ru.mes.dnevnik.R.attr.closeIconEndPadding, ru.mes.dnevnik.R.attr.closeIconSize, ru.mes.dnevnik.R.attr.closeIconStartPadding, ru.mes.dnevnik.R.attr.closeIconTint, ru.mes.dnevnik.R.attr.closeIconVisible, ru.mes.dnevnik.R.attr.ensureMinTouchTargetSize, ru.mes.dnevnik.R.attr.hideMotionSpec, ru.mes.dnevnik.R.attr.iconEndPadding, ru.mes.dnevnik.R.attr.iconStartPadding, ru.mes.dnevnik.R.attr.rippleColor, ru.mes.dnevnik.R.attr.shapeAppearance, ru.mes.dnevnik.R.attr.shapeAppearanceOverlay, ru.mes.dnevnik.R.attr.showMotionSpec, ru.mes.dnevnik.R.attr.textEndPadding, ru.mes.dnevnik.R.attr.textStartPadding};
    public static final int[] f = {ru.mes.dnevnik.R.attr.clockFaceBackgroundColor, ru.mes.dnevnik.R.attr.clockNumberTextColor};
    public static final int[] g = {ru.mes.dnevnik.R.attr.clockHandColor, ru.mes.dnevnik.R.attr.materialCircleRadius, ru.mes.dnevnik.R.attr.selectorSize};
    public static final int[] h = {ru.mes.dnevnik.R.attr.behavior_autoHide, ru.mes.dnevnik.R.attr.behavior_autoShrink};
    public static final int[] i = {ru.mes.dnevnik.R.attr.behavior_autoHide};
    public static final int[] j = {R.attr.foreground, R.attr.foregroundGravity, ru.mes.dnevnik.R.attr.foregroundInsidePadding};
    public static final int[] k = {ru.mes.dnevnik.R.attr.backgroundInsetBottom, ru.mes.dnevnik.R.attr.backgroundInsetEnd, ru.mes.dnevnik.R.attr.backgroundInsetStart, ru.mes.dnevnik.R.attr.backgroundInsetTop, ru.mes.dnevnik.R.attr.backgroundTint};
    public static final int[] l = {R.attr.inputType, R.attr.popupElevation, ru.mes.dnevnik.R.attr.dropDownBackgroundTint, ru.mes.dnevnik.R.attr.simpleItemLayout, ru.mes.dnevnik.R.attr.simpleItemSelectedColor, ru.mes.dnevnik.R.attr.simpleItemSelectedRippleColor, ru.mes.dnevnik.R.attr.simpleItems};
    public static final int[] m = {R.attr.background, R.attr.insetLeft, R.attr.insetRight, R.attr.insetTop, R.attr.insetBottom, R.attr.checkable, ru.mes.dnevnik.R.attr.backgroundTint, ru.mes.dnevnik.R.attr.backgroundTintMode, ru.mes.dnevnik.R.attr.cornerRadius, ru.mes.dnevnik.R.attr.elevation, ru.mes.dnevnik.R.attr.icon, ru.mes.dnevnik.R.attr.iconGravity, ru.mes.dnevnik.R.attr.iconPadding, ru.mes.dnevnik.R.attr.iconSize, ru.mes.dnevnik.R.attr.iconTint, ru.mes.dnevnik.R.attr.iconTintMode, ru.mes.dnevnik.R.attr.rippleColor, ru.mes.dnevnik.R.attr.shapeAppearance, ru.mes.dnevnik.R.attr.shapeAppearanceOverlay, ru.mes.dnevnik.R.attr.strokeColor, ru.mes.dnevnik.R.attr.strokeWidth, ru.mes.dnevnik.R.attr.toggleCheckedStateOnClick};
    public static final int[] n = {R.attr.enabled, ru.mes.dnevnik.R.attr.checkedButton, ru.mes.dnevnik.R.attr.selectionRequired, ru.mes.dnevnik.R.attr.singleSelection};
    public static final int[] o = {R.attr.windowFullscreen, ru.mes.dnevnik.R.attr.backgroundTint, ru.mes.dnevnik.R.attr.dayInvalidStyle, ru.mes.dnevnik.R.attr.daySelectedStyle, ru.mes.dnevnik.R.attr.dayStyle, ru.mes.dnevnik.R.attr.dayTodayStyle, ru.mes.dnevnik.R.attr.nestedScrollable, ru.mes.dnevnik.R.attr.rangeFillColor, ru.mes.dnevnik.R.attr.yearSelectedStyle, ru.mes.dnevnik.R.attr.yearStyle, ru.mes.dnevnik.R.attr.yearTodayStyle};
    public static final int[] p = {R.attr.insetLeft, R.attr.insetRight, R.attr.insetTop, R.attr.insetBottom, ru.mes.dnevnik.R.attr.itemFillColor, ru.mes.dnevnik.R.attr.itemShapeAppearance, ru.mes.dnevnik.R.attr.itemShapeAppearanceOverlay, ru.mes.dnevnik.R.attr.itemStrokeColor, ru.mes.dnevnik.R.attr.itemStrokeWidth, ru.mes.dnevnik.R.attr.itemTextColor};
    public static final int[] q = {R.attr.button, ru.mes.dnevnik.R.attr.buttonCompat, ru.mes.dnevnik.R.attr.buttonIcon, ru.mes.dnevnik.R.attr.buttonIconTint, ru.mes.dnevnik.R.attr.buttonIconTintMode, ru.mes.dnevnik.R.attr.buttonTint, ru.mes.dnevnik.R.attr.centerIfNoTextEnabled, ru.mes.dnevnik.R.attr.checkedState, ru.mes.dnevnik.R.attr.errorAccessibilityLabel, ru.mes.dnevnik.R.attr.errorShown, ru.mes.dnevnik.R.attr.useMaterialThemeColors};
    public static final int[] r = {ru.mes.dnevnik.R.attr.buttonTint, ru.mes.dnevnik.R.attr.useMaterialThemeColors};
    public static final int[] s = {ru.mes.dnevnik.R.attr.shapeAppearance, ru.mes.dnevnik.R.attr.shapeAppearanceOverlay};
    public static final int[] t = {R.attr.letterSpacing, R.attr.lineHeight, ru.mes.dnevnik.R.attr.lineHeight};
    public static final int[] u = {R.attr.textAppearance, R.attr.lineHeight, ru.mes.dnevnik.R.attr.lineHeight};
    public static final int[] v = {ru.mes.dnevnik.R.attr.backgroundTint, ru.mes.dnevnik.R.attr.clockIcon, ru.mes.dnevnik.R.attr.keyboardIcon};
    public static final int[] w = {ru.mes.dnevnik.R.attr.logoAdjustViewBounds, ru.mes.dnevnik.R.attr.logoScaleType, ru.mes.dnevnik.R.attr.navigationIconTint, ru.mes.dnevnik.R.attr.subtitleCentered, ru.mes.dnevnik.R.attr.titleCentered};
    public static final int[] x = {ru.mes.dnevnik.R.attr.materialCircleRadius};
    public static final int[] y = {ru.mes.dnevnik.R.attr.behavior_overlapTop};
    public static final int[] z = {ru.mes.dnevnik.R.attr.cornerFamily, ru.mes.dnevnik.R.attr.cornerFamilyBottomLeft, ru.mes.dnevnik.R.attr.cornerFamilyBottomRight, ru.mes.dnevnik.R.attr.cornerFamilyTopLeft, ru.mes.dnevnik.R.attr.cornerFamilyTopRight, ru.mes.dnevnik.R.attr.cornerSize, ru.mes.dnevnik.R.attr.cornerSizeBottomLeft, ru.mes.dnevnik.R.attr.cornerSizeBottomRight, ru.mes.dnevnik.R.attr.cornerSizeTopLeft, ru.mes.dnevnik.R.attr.cornerSizeTopRight};
    public static final int[] A = {R.attr.maxWidth, R.attr.maxHeight, R.attr.elevation, ru.mes.dnevnik.R.attr.backgroundTint, ru.mes.dnevnik.R.attr.behavior_draggable, ru.mes.dnevnik.R.attr.coplanarSiblingViewId, ru.mes.dnevnik.R.attr.shapeAppearance, ru.mes.dnevnik.R.attr.shapeAppearanceOverlay};
    public static final int[] B = {R.attr.maxWidth, ru.mes.dnevnik.R.attr.actionTextColorAlpha, ru.mes.dnevnik.R.attr.animationMode, ru.mes.dnevnik.R.attr.backgroundOverlayColorAlpha, ru.mes.dnevnik.R.attr.backgroundTint, ru.mes.dnevnik.R.attr.backgroundTintMode, ru.mes.dnevnik.R.attr.elevation, ru.mes.dnevnik.R.attr.maxActionInlineWidth, ru.mes.dnevnik.R.attr.shapeAppearance, ru.mes.dnevnik.R.attr.shapeAppearanceOverlay};
    public static final int[] C = {R.attr.textSize, R.attr.typeface, R.attr.textStyle, R.attr.textColor, R.attr.textColorHint, R.attr.textColorLink, R.attr.shadowColor, R.attr.shadowDx, R.attr.shadowDy, R.attr.shadowRadius, R.attr.fontFamily, R.attr.textFontWeight, ru.mes.dnevnik.R.attr.fontFamily, ru.mes.dnevnik.R.attr.fontVariationSettings, ru.mes.dnevnik.R.attr.textAllCaps, ru.mes.dnevnik.R.attr.textLocale};
    public static final int[] D = {ru.mes.dnevnik.R.attr.textInputLayoutFocusedRectEnabled};
    public static final int[] E = {R.attr.enabled, R.attr.textColorHint, R.attr.maxWidth, R.attr.minWidth, R.attr.hint, R.attr.maxEms, R.attr.minEms, ru.mes.dnevnik.R.attr.boxBackgroundColor, ru.mes.dnevnik.R.attr.boxBackgroundMode, ru.mes.dnevnik.R.attr.boxCollapsedPaddingTop, ru.mes.dnevnik.R.attr.boxCornerRadiusBottomEnd, ru.mes.dnevnik.R.attr.boxCornerRadiusBottomStart, ru.mes.dnevnik.R.attr.boxCornerRadiusTopEnd, ru.mes.dnevnik.R.attr.boxCornerRadiusTopStart, ru.mes.dnevnik.R.attr.boxStrokeColor, ru.mes.dnevnik.R.attr.boxStrokeErrorColor, ru.mes.dnevnik.R.attr.boxStrokeWidth, ru.mes.dnevnik.R.attr.boxStrokeWidthFocused, ru.mes.dnevnik.R.attr.counterEnabled, ru.mes.dnevnik.R.attr.counterMaxLength, ru.mes.dnevnik.R.attr.counterOverflowTextAppearance, ru.mes.dnevnik.R.attr.counterOverflowTextColor, ru.mes.dnevnik.R.attr.counterTextAppearance, ru.mes.dnevnik.R.attr.counterTextColor, ru.mes.dnevnik.R.attr.cursorColor, ru.mes.dnevnik.R.attr.cursorErrorColor, ru.mes.dnevnik.R.attr.endIconCheckable, ru.mes.dnevnik.R.attr.endIconContentDescription, ru.mes.dnevnik.R.attr.endIconDrawable, ru.mes.dnevnik.R.attr.endIconMinSize, ru.mes.dnevnik.R.attr.endIconMode, ru.mes.dnevnik.R.attr.endIconScaleType, ru.mes.dnevnik.R.attr.endIconTint, ru.mes.dnevnik.R.attr.endIconTintMode, ru.mes.dnevnik.R.attr.errorAccessibilityLiveRegion, ru.mes.dnevnik.R.attr.errorContentDescription, ru.mes.dnevnik.R.attr.errorEnabled, ru.mes.dnevnik.R.attr.errorIconDrawable, ru.mes.dnevnik.R.attr.errorIconTint, ru.mes.dnevnik.R.attr.errorIconTintMode, ru.mes.dnevnik.R.attr.errorTextAppearance, ru.mes.dnevnik.R.attr.errorTextColor, ru.mes.dnevnik.R.attr.expandedHintEnabled, ru.mes.dnevnik.R.attr.helperText, ru.mes.dnevnik.R.attr.helperTextEnabled, ru.mes.dnevnik.R.attr.helperTextTextAppearance, ru.mes.dnevnik.R.attr.helperTextTextColor, ru.mes.dnevnik.R.attr.hintAnimationEnabled, ru.mes.dnevnik.R.attr.hintEnabled, ru.mes.dnevnik.R.attr.hintTextAppearance, ru.mes.dnevnik.R.attr.hintTextColor, ru.mes.dnevnik.R.attr.passwordToggleContentDescription, ru.mes.dnevnik.R.attr.passwordToggleDrawable, ru.mes.dnevnik.R.attr.passwordToggleEnabled, ru.mes.dnevnik.R.attr.passwordToggleTint, ru.mes.dnevnik.R.attr.passwordToggleTintMode, ru.mes.dnevnik.R.attr.placeholderText, ru.mes.dnevnik.R.attr.placeholderTextAppearance, ru.mes.dnevnik.R.attr.placeholderTextColor, ru.mes.dnevnik.R.attr.prefixText, ru.mes.dnevnik.R.attr.prefixTextAppearance, ru.mes.dnevnik.R.attr.prefixTextColor, ru.mes.dnevnik.R.attr.shapeAppearance, ru.mes.dnevnik.R.attr.shapeAppearanceOverlay, ru.mes.dnevnik.R.attr.startIconCheckable, ru.mes.dnevnik.R.attr.startIconContentDescription, ru.mes.dnevnik.R.attr.startIconDrawable, ru.mes.dnevnik.R.attr.startIconMinSize, ru.mes.dnevnik.R.attr.startIconScaleType, ru.mes.dnevnik.R.attr.startIconTint, ru.mes.dnevnik.R.attr.startIconTintMode, ru.mes.dnevnik.R.attr.suffixText, ru.mes.dnevnik.R.attr.suffixTextAppearance, ru.mes.dnevnik.R.attr.suffixTextColor};
    public static final int[] F = {R.attr.textAppearance, ru.mes.dnevnik.R.attr.enforceMaterialTheme, ru.mes.dnevnik.R.attr.enforceTextAppearance};
}
