package defpackage;

/* loaded from: classes.dex */
public final class UW1 implements MW1 {
    public static final WO1 A;
    public static final WO1 B;
    public static final WO1 C;
    public static final WO1 D;
    public static final WO1 E;
    public static final WO1 F;
    public static final WO1 G;
    public static final WO1 H;
    public static final WO1 I;
    public static final WO1 J;
    public static final WO1 K;
    public static final WO1 L;
    public static final WO1 M;
    public static final WO1 N;
    public static final WO1 O;
    public static final WO1 P;
    public static final WO1 Q;
    public static final WO1 R;
    public static final WO1 S;
    public static final WO1 T;
    public static final WO1 U;
    public static final WO1 V;
    public static final WO1 W;
    public static final WO1 X;
    public static final WO1 Y;
    public static final WO1 Z;
    public static final WO1 a;
    public static final WO1 a0;
    public static final WO1 b;
    public static final WO1 b0;
    public static final WO1 c;
    public static final WO1 c0;
    public static final WO1 d;
    public static final WO1 d0;
    public static final WO1 e;
    public static final WO1 e0;
    public static final WO1 f;
    public static final WO1 f0;
    public static final WO1 g;
    public static final WO1 g0;
    public static final WO1 h;
    public static final WO1 h0;
    public static final WO1 i;
    public static final WO1 i0;
    public static final WO1 j;
    public static final WO1 j0;
    public static final WO1 k;
    public static final WO1 k0;
    public static final WO1 l;
    public static final WO1 l0;
    public static final WO1 m;
    public static final WO1 m0;
    public static final WO1 n;
    public static final WO1 n0;
    public static final WO1 o;
    public static final WO1 o0;
    public static final WO1 p;
    public static final WO1 q;
    public static final WO1 r;
    public static final WO1 s;
    public static final WO1 t;
    public static final WO1 u;
    public static final WO1 v;
    public static final WO1 w;
    public static final WO1 x;
    public static final WO1 y;
    public static final WO1 z;

    static {
        VG vg = new VG(AbstractC7022sO1.a("com.google.android.gms.measurement"), "", "", true, true);
        a = vg.q(10000L, "measurement.ad_id_cache_time");
        b = vg.q(3600000L, "measurement.app_uninstalled_additional_ad_id_cache_time");
        c = vg.s("measurement.config.bundle_for_all_apps_on_backgrounded", true);
        d = vg.q(100L, "measurement.max_bundles_per_iteration");
        e = vg.q(86400000L, "measurement.config.cache_time");
        vg.r("measurement.log_tag", "FA");
        f = vg.r("measurement.config.url_authority", "app-measurement.com");
        g = vg.r("measurement.config.url_scheme", "https");
        h = vg.q(1000L, "measurement.upload.debug_upload_interval");
        i = vg.q(3600000L, "measurement.session.engagement_interval");
        j = vg.r("measurement.rb.attribution.event_params", "value|currency");
        vg.q(0L, "measurement.id.rb.attribution.app_allowlist");
        vg.q(0L, "measurement.id.rb.attribution.notify_app_delay_millis");
        vg.q(0L, "measurement.id.rb.attribution.client.min_time_after_boot_seconds");
        k = vg.q(605000L, "measurement.upload.google_signal_max_queue_time");
        l = vg.r("measurement.sgtm.google_signal.url", "https://app-measurement.com/s/d");
        m = vg.q(4L, "measurement.lifetimevalue.max_currency_tracked");
        n = vg.q(1L, "measurement.dma_consent.max_daily_dcu_realtime_events");
        o = vg.q(500L, "measurement.upload.max_event_parameter_value_length");
        p = vg.q(100000L, "measurement.store.max_stored_events_per_app");
        q = vg.q(50L, "measurement.experiment.max_ids");
        r = vg.q(200L, "measurement.audience.filter_result_max_count");
        s = vg.q(27L, "measurement.upload.max_item_scoped_custom_parameters");
        t = vg.q(1000L, "measurement.rb.max_trigger_registrations_per_day");
        u = vg.q(0L, "measurement.rb.attribution.max_trigger_uris_queried_at_once");
        v = vg.q(7L, "measurement.rb.attribution.client.min_ad_services_version");
        w = vg.q(60000L, "measurement.alarm_manager.minimum_interval");
        x = vg.q(500L, "measurement.upload.minimum_delay");
        y = vg.q(86400000L, "measurement.monitoring.sample_period_millis");
        z = vg.q(0L, "measurement.rb.attribution.notify_app_delay_millis");
        A = vg.s("measurement.config.notify_trigger_uris_on_backgrounded", true);
        B = vg.r("measurement.rb.attribution.app_allowlist", "com.labpixies.flood,com.sofascore.results,games.spearmint.triplecrush,com.block.juggle,io.supercent.linkedcubic,com.cdtg.gunsound,com.corestudios.storemanagementidle,com.cdgames.fidget3d,io.supercent.burgeridle,io.supercent.pizzaidle,jp.ne.ibis.ibispaintx.app,com.dencreak.dlcalculator,com.ebay.kleinanzeigen,de.wetteronline.wetterapp,com.game.shape.shift,com.champion.cubes,bubbleshooter.orig,com.wolt.android,com.master.hotelmaster,com.games.bus.arrival,com.playstrom.dop2,com.huuuge.casino.slots,com.ig.spider.fighting,com.jura.coloring.page,com.rikkogame.ragdoll2,com.ludo.king,com.sigma.prank.sound.haircut,com.crazy.block.robo.monster.cliffs.craft,com.fugo.wow,com.maps.locator.gps.gpstracker.phone,com.gamovation.tileclub,com.pronetis.ironball2,com.meesho.supply,pdf.pdfreader.viewer.editor.free,com.dino.race.master,com.ig.moto.racing,ai.photo.enhancer.photoclear,com.duolingo,com.candle.magic_piano,com.free.vpn.super.hotspot.open,sg.bigo.live,com.cdg.tictactoe,com.zhiliaoapp.musically.go,com.wildspike.wormszone,com.mast.status.video.edit,com.vyroai.photoeditorone,com.pujiagames.deeeersimulator,com.superbinogo.jungleboyadventure,com.trustedapp.pdfreaderpdfviewer,com.artimind.aiart.artgenerator.artavatar,de.cellular.ottohybrid,com.zeptolab.cats.google,in.crossy.daily_crossword");
        C = vg.q(10000L, "measurement.upload.realtime_upload_interval");
        D = vg.q(604800000L, "measurement.upload.refresh_blacklisted_config_interval");
        vg.q(3600000L, "measurement.config.cache_time.service");
        E = vg.q(5000L, "measurement.service_client.idle_disconnect_millis");
        vg.r("measurement.log_tag.service", "FA-SVC");
        vg.r("measurement.sgtm.app_allowlist", "*");
        F = vg.r("measurement.sgtm.service_upload_apps_list", "de.zalando.mobile");
        G = vg.q(10L, "measurement.sgtm.upload.batches_retrieval_limit");
        H = vg.q(5000L, "measurement.sgtm.upload.max_queued_batches");
        I = vg.q(600000L, "measurement.sgtm.upload.min_delay_after_background");
        J = vg.q(1000L, "measurement.sgtm.upload.min_delay_after_broadcast");
        K = vg.q(5000L, "measurement.sgtm.upload.min_delay_after_startup");
        L = vg.q(1800000L, "measurement.sgtm.upload.retry_interval");
        M = vg.q(21600000L, "measurement.sgtm.upload.retry_max_wait");
        N = vg.q(86400000L, "measurement.upload.stale_data_deletion_interval");
        O = vg.q(16L, "measurement.rb.attribution.max_retry_delay_seconds");
        P = vg.q(0L, "measurement.rb.attribution.client.min_time_after_boot_seconds");
        Q = vg.r("measurement.rb.attribution.uri_authority", "google-analytics.com");
        R = vg.q(864000000L, "measurement.rb.attribution.max_queue_time");
        S = vg.r("measurement.rb.attribution.uri_path", "privacy-sandbox/register-app-conversion");
        T = vg.r("measurement.rb.attribution.query_parameters_to_remove", "");
        U = vg.r("measurement.rb.attribution.uri_scheme", "https");
        V = vg.q(604800000L, "measurement.sdk.attribution.cache.ttl");
        W = vg.q(7200000L, "measurement.redaction.app_instance_id.ttl");
        X = vg.q(43200000L, "measurement.upload.backoff_period");
        Y = vg.q(15000L, "measurement.upload.initial_upload_delay_time");
        Z = vg.q(3600000L, "measurement.upload.interval");
        a0 = vg.q(65536L, "measurement.upload.max_bundle_size");
        b0 = vg.q(100L, "measurement.upload.max_bundles");
        c0 = vg.q(500L, "measurement.upload.max_conversions_per_day");
        d0 = vg.q(1000L, "measurement.upload.max_error_events_per_day");
        e0 = vg.q(1000L, "measurement.upload.max_events_per_bundle");
        f0 = vg.q(100000L, "measurement.upload.max_events_per_day");
        g0 = vg.q(50000L, "measurement.upload.max_public_events_per_day");
        h0 = vg.q(518400000L, "measurement.upload.max_queue_time");
        i0 = vg.q(10L, "measurement.upload.max_realtime_events_per_day");
        j0 = vg.q(65536L, "measurement.upload.max_batch_size");
        k0 = vg.q(6L, "measurement.upload.retry_count");
        l0 = vg.q(1800000L, "measurement.upload.retry_time");
        m0 = vg.r("measurement.upload.url", "https://app-measurement.com/a");
        n0 = vg.q(3600000L, "measurement.upload.window_interval");
        o0 = vg.r("measurement.rb.attribution.user_properties", "_npa,npa|_fot,fot");
    }
}
